### ISSUE TITLE
Is there a specific reason for why Bare Metal Servers are not available in Norway

### ISSUE THREAD

**Issue by ibmchas** [ibm-cloud-docs/resources#12]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
_Documentation mismatch between which infrastructure services availabe in Norway DC, Cloud Portal and Cloud CLI states Bare Metal Server is available in Norway, Documentation states it is not, please clarify if any limitations apply._

2. Is this issue in reference to a specific page? If so, please provide a link.
_https://cloud.ibm.com/docs/resources?topic=resources-services_region#paas-services_

3. Do you have a suggestion about how to resolve the issue?
_Offering Manager should confirm that Bare Metal Servers is available in Norway DC_

**Comment by hlucey** [comment]
Reached out and resolving internally.
