### ISSUE TITLE
Downgrading Plan

### ISSUE THREAD

**Issue by MaribelDoiz** [ibm-cloud-docs/resources#14]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by MaribelDoiz** [comment]
I need to move to "Lite" plan from "Plus Trial" and I cannot do it. I am IBM employee. This is the message I have got.
![image](https://user-images.githubusercontent.com/64129963/83623971-52babf00-a592-11ea-9ef1-cb82a87263fd.png)

**Comment by mekaufman** [comment]
@MaribelDoiz Please reach out on slack to @mkaufman or @hlucey, and we can work on directing you to someone who might be able to help.
