### ISSUE TITLE
IBM Clound account is currently suspended or canceled

### ISSUE THREAD

**Issue by LanaRobertaKoutsoukos** [ibm-cloud-docs/resources#16]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing? 
I received this message: The account is currently suspended or canceled. Contact your account owner to resolve.

2. Is this issue in reference to a specific page? If so, please provide a link. https://cloud.ibm.com/iam/overview

3. Do you have a suggestion about how to resolve the issue? 
I already requested  an internal IBM Cloud account, but it's still pending since June 1st.
Your first-line manager approved your internal IBM Cloud account request. The request is now pending cost recovery configuration by the IBM Cloud Sales Ops team and you will be notified once it is complete.

**Comment by mekaufman** [comment]
@LanaRobertaKoutsoukos I have reached out internally. Thanks.
